/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mrrobot.signin_signup_form;

import com.mysql.cj.callback.UsernameCallback;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author bickkysahani
 */
public class changepw extends javax.swing.JFrame {

    /**
     * Creates new form changepw
     */
    public static String name;

    public changepw(String username) {
        initComponents();
        this.name = username;
        System.out.println("username: " + name);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnChangePw = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        newpassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1193, 640));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(39, 35, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel5.setText("SUBMIT");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, 20));

        btnChangePw.setIcon(new javax.swing.ImageIcon("/home/bickkysahani/NetBeansProjects/signin_signup_form/images/btn.png")); // NOI18N
        btnChangePw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangePw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangePwMouseClicked(evt);
            }
        });
        jPanel1.add(btnChangePw, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 170, 60));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter a new password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 280, 100));

        newpassword.setBackground(new java.awt.Color(39, 35, 65));
        newpassword.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        newpassword.setForeground(new java.awt.Color(204, 204, 204));
        newpassword.setText("password");
        newpassword.setBorder(null);
        newpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        newpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newpasswordFocusGained(evt);
            }
        });
        newpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(newpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 310, 50));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 270, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 980, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newpasswordFocusGained
        // TODO add your handling code here:
        this.newpassword.setText("");
    }//GEN-LAST:event_newpasswordFocusGained

    private void newpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpasswordActionPerformed

    private void btnChangePwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePwMouseClicked

        System.out.println("username cp: " + name);
        String pass = String.valueOf(newpassword.getPassword());
        System.out.println("new pass: " + pass);
        Connection dbconn;
        dbconn = dbconnection.ConnectDB();
        String update = "Update users set password=? where username=?";
        PreparedStatement st = null;
        st = (PreparedStatement) dbconn.prepareStatement(update);
        st.setString(1, pass);
        st.setString(2, name);
        st.executeUpdate();
        JOptionPane.showMessageDialog(btnChangePw, "Password has been successfully changed");
        dispose();
        signin n = new signin();
        n.setTitle("Sign in Form");
        n.setLocationRelativeTo(null);
        n.setVisible(true);

    }//GEN-LAST:event_btnChangePwMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changepw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changepw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changepw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changepw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changepw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnChangePw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField newpassword;
    // End of variables declaration//GEN-END:variables


}
